"""
Supplement Optimization Model

This module solves the supplement optimization problem where the goal is to find
the minimum number of pills/capsules/gummies to take while meeting daily nutritional
requirements.

The problem can be formulated as a linear programming problem:

Minimize: sum of all supplement quantities (total number of pills)
Subject to: meeting minimum daily requirements for each nutrient

This is essentially a variant of the classic "diet problem" in operations research.

IMPORTANT DISCLAIMER:
This tool is for educational and research purposes only. It is NOT intended to
provide medical advice, diagnosis, or treatment recommendations. The nutritional
requirements and supplement suggestions generated by this model should NOT be used
as a substitute for professional medical advice.

ALWAYS consult with a qualified healthcare provider, registered dietitian, or
physician before making any changes to your supplement regimen or diet. Individual
nutritional needs vary based on age, health conditions, medications, activity level,
and other factors that this model cannot account for.

The authors and contributors of this software assume NO RESPONSIBILITY for any
health consequences resulting from the use of this tool.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
from scipy.optimize import linprog


@dataclass
class Supplement:
    """Represents a supplement product with its nutritional content."""

    name: str
    brand: str
    form: str  # "pill", "capsule", "gummy", "tablet"
    nutrients: Dict[str, float]  # nutrient_name -> amount per unit
    cost_per_unit: Optional[float] = None  # optional cost information

    def __str__(self):
        return f"{self.brand} {self.name} ({self.form})"


@dataclass
class DailyRequirement:
    """Represents daily nutritional requirements for a person."""

    age: int
    gender: str  # "male" or "female"
    requirements: Dict[str, float]  # nutrient_name -> minimum daily amount

    def __str__(self):
        return f"{self.gender.title()}, age {self.age}"


class SupplementOptimizer:
    """
    Optimizes supplement intake to minimize total number of pills while
    meeting daily nutritional requirements.
    """

    def __init__(self):
        self.supplements: List[Supplement] = []
        self.daily_req: Optional[DailyRequirement] = None

    def add_supplement(self, supplement: Supplement) -> None:
        """Add a supplement option to the available choices."""
        self.supplements.append(supplement)

    def set_daily_requirements(self, daily_req: DailyRequirement) -> None:
        """Set the daily nutritional requirements."""
        self.daily_req = daily_req

    def get_all_nutrients(self) -> List[str]:
        """Get all unique nutrients across all supplements and requirements."""
        nutrients = set()

        # From supplements
        for supp in self.supplements:
            nutrients.update(supp.nutrients.keys())

        # From requirements
        if self.daily_req:
            nutrients.update(self.daily_req.requirements.keys())

        return sorted(list(nutrients))

    def create_nutritional_matrix(self) -> Tuple[np.ndarray, List[str], List[str]]:
        """
        Create the nutritional content matrix for optimization.

        Returns:
            A: Matrix where A[i,j] = amount of nutrient i in supplement j
            nutrient_names: List of nutrient names (rows)
            supplement_names: List of supplement names (columns)
        """
        nutrients = self.get_all_nutrients()
        supplement_names = [str(supp) for supp in self.supplements]

        # Create matrix
        A = np.zeros((len(nutrients), len(self.supplements)))

        for j, supplement in enumerate(self.supplements):
            for i, nutrient in enumerate(nutrients):
                A[i, j] = supplement.nutrients.get(nutrient, 0.0)

        return A, nutrients, supplement_names

    def solve_minimum_pills(self, allow_fractional: bool = True) -> Dict:
        """
        Solve the supplement optimization problem to minimize total number of pills.

        Args:
            allow_fractional: If True, allows fractional pills (e.g., 0.5 pills)
                            If False, requires integer solutions

        Returns:
            Dictionary with optimization results
        """
        if not self.supplements:
            raise ValueError("No supplements added")
        if not self.daily_req:
            raise ValueError("Daily requirements not set")

        A, nutrients, supplement_names = self.create_nutritional_matrix()

        # Objective: minimize sum of all supplement quantities (c = [1, 1, ..., 1])
        c = np.ones(len(self.supplements))

        # Constraint matrix: A_ub @ x >= b_ub (we need >= constraints)
        # linprog expects <= constraints, so we use -A @ x <= -b
        A_ub = -A
        if self.daily_req is not None:
            b_ub = np.array(
                [
                    -self.daily_req.requirements.get(nutrient, 0.0)
                    for nutrient in nutrients
                ]
            )
        else:
            b_ub = np.zeros(len(nutrients))

        # Bounds: x >= 0 (non-negative supplement quantities)
        bounds = [(0, None) for _ in range(len(self.supplements))]

        # Solve the linear program
        if allow_fractional:
            result = linprog(
                c,
                A_ub=A_ub,
                b_ub=b_ub,
                bounds=bounds,
                method="highs",
                options={"disp": False},
            )
        else:
            # For integer programming, we'll use a simple rounding approach
            # In practice, you might want to use specialized IP solvers
            fractional_result = linprog(
                c,
                A_ub=A_ub,
                b_ub=b_ub,
                bounds=bounds,
                method="highs",
                options={"disp": False},
            )
            if not fractional_result.success:
                return self._format_failure_result()

            # Round up to ensure constraints are still satisfied
            x_rounded = np.ceil(fractional_result.x)

            # Create a simple result object
            class IntegerResult:
                def __init__(self, success: bool, x: np.ndarray, fun: float):
                    self.success = success
                    self.x = x
                    self.fun = fun

            result = IntegerResult(True, x_rounded, float(np.sum(x_rounded)))

        if not result.success:
            return self._format_failure_result()

        return self._format_success_result(result, nutrients, supplement_names, A)

    def _format_failure_result(self) -> Dict:
        """Format result when optimization fails."""
        return {
            "success": False,
            "message": "No feasible solution found",
            "total_pills": None,
            "supplement_plan": None,
            "nutrient_analysis": None,
        }

    def _format_success_result(
        self, result, nutrients: List[str], supplement_names: List[str], A: np.ndarray
    ) -> Dict:
        """Format successful optimization result."""
        x = result.x
        total_pills = result.fun

        # Create supplement plan
        supplement_plan = []
        for i, quantity in enumerate(x):
            if quantity > 1e-6:  # Only include non-zero quantities
                supplement_plan.append(
                    {
                        "supplement": supplement_names[i],
                        "quantity": round(quantity, 3),
                        "form": self.supplements[i].form,
                    }
                )

        # Calculate actual nutrient intake
        actual_intake = A @ x
        nutrient_analysis = []

        if self.daily_req is not None:
            for i, nutrient in enumerate(nutrients):
                required = self.daily_req.requirements.get(nutrient, 0.0)
                actual = actual_intake[i]

                if required > 0:  # Only show nutrients that are required
                    nutrient_analysis.append(
                        {
                            "nutrient": nutrient,
                            "required": required,
                            "actual": round(actual, 3),
                            "surplus": round(max(0, actual - required), 3),
                            "percentage_of_requirement": (
                                round((actual / required) * 100, 1)
                                if required > 0
                                else 0
                            ),
                        }
                    )

        return {
            "success": True,
            "total_pills": round(total_pills, 3),
            "supplement_plan": supplement_plan,
            "nutrient_analysis": nutrient_analysis,
            "message": f"Optimal solution found: {total_pills:.3f} total pills/units",
        }

    def solve_minimum_cost(self) -> Dict:
        """
        Solve to minimize total cost instead of number of pills.
        Requires cost information for all supplements.
        """
        if not all(supp.cost_per_unit is not None for supp in self.supplements):
            raise ValueError("Cost information required for all supplements")

        A, nutrients, supplement_names = self.create_nutritional_matrix()

        # Objective: minimize total cost
        c = np.array([supp.cost_per_unit for supp in self.supplements])

        # Same constraints as minimum pills problem
        A_ub = -A
        if self.daily_req is not None:
            b_ub = np.array(
                [
                    -self.daily_req.requirements.get(nutrient, 0.0)
                    for nutrient in nutrients
                ]
            )
        else:
            b_ub = np.zeros(len(nutrients))
        bounds = [(0, None) for _ in range(len(self.supplements))]

        result = linprog(
            c,
            A_ub=A_ub,
            b_ub=b_ub,
            bounds=bounds,
            method="highs",
            options={"disp": False},
        )

        if not result.success:
            return self._format_failure_result()

        # Format result with cost information
        result_dict = self._format_success_result(
            result, nutrients, supplement_names, A
        )
        result_dict["total_cost"] = round(result.fun, 2)
        result_dict["message"] = f"Optimal solution found: ${result.fun:.2f} total cost"

        # Add cost information to supplement plan
        for i, plan_item in enumerate(result_dict["supplement_plan"]):
            supp_idx = supplement_names.index(plan_item["supplement"])
            cost_per_unit = self.supplements[supp_idx].cost_per_unit
            total_cost = plan_item["quantity"] * cost_per_unit
            plan_item["cost_per_unit"] = cost_per_unit
            plan_item["total_cost"] = round(total_cost, 2)

        return result_dict

    def print_solution(self, result: Dict) -> None:
        """Print the optimization solution in a readable format."""
        if not result["success"]:
            print(f"❌ {result['message']}")
            return

        print(f"✅ {result['message']}")
        print(f"\n📋 Daily Requirements: {self.daily_req}")
        print(f"💊 Total Pills/Units: {result['total_pills']}")

        if "total_cost" in result:
            print(f"💰 Total Cost: ${result['total_cost']}")

        print("\n📝 Supplement Plan:")
        for item in result["supplement_plan"]:
            quantity_str = (
                f"{item['quantity']:.1f}"
                if item["quantity"] != int(item["quantity"])
                else str(int(item["quantity"]))
            )

            if "total_cost" in item:
                print(
                    f"  • {quantity_str} {item['form']}(s) of {item['supplement']} (${item['total_cost']:.2f})"
                )
            else:
                print(f"  • {quantity_str} {item['form']}(s) of {item['supplement']}")

        print("\n🔬 Nutrient Analysis:")
        for nutrient in result["nutrient_analysis"]:
            surplus_str = (
                f" (+{nutrient['surplus']} surplus)" if nutrient["surplus"] > 0 else ""
            )
            print(
                f"  • {nutrient['nutrient']}: {nutrient['actual']}/{nutrient['required']} "
                f"({nutrient['percentage_of_requirement']}%){surplus_str}"
            )


def create_sample_data() -> Tuple[List[Supplement], DailyRequirement]:
    """Create sample supplement data and daily requirements for demonstration."""

    # Sample supplements with realistic nutritional content
    supplements = [
        Supplement(
            name="Multivitamin",
            brand="NatureMade",
            form="tablet",
            nutrients={
                "Vitamin A": 900,  # mcg
                "Vitamin C": 90,  # mg
                "Vitamin D": 20,  # mcg
                "Vitamin E": 15,  # mg
                "Vitamin B12": 2.4,  # mcg
                "Calcium": 162,  # mg
                "Iron": 8,  # mg
                "Magnesium": 100,  # mg
            },
            cost_per_unit=0.15,
        ),
        Supplement(
            name="Omega-3",
            brand="Nordic Naturals",
            form="capsule",
            nutrients={
                "Omega-3 EPA": 325,  # mg
                "Omega-3 DHA": 225,  # mg
                "Vitamin E": 5,  # mg
            },
            cost_per_unit=0.75,
        ),
        Supplement(
            name="Magnesium Glycinate",
            brand="Thorne",
            form="capsule",
            nutrients={
                "Magnesium": 200,  # mg
            },
            cost_per_unit=0.45,
        ),
        Supplement(
            name="Calcium + D3",
            brand="Kirkland",
            form="tablet",
            nutrients={
                "Calcium": 600,  # mg
                "Vitamin D": 20,  # mcg
            },
            cost_per_unit=0.08,
        ),
        Supplement(
            name="B12 Sublingual",
            brand="Jarrow",
            form="tablet",
            nutrients={
                "Vitamin B12": 1000,  # mcg
            },
            cost_per_unit=0.12,
        ),
        Supplement(
            name="Probiotic",
            brand="Garden of Life",
            form="capsule",
            nutrients={
                "Probiotics": 50,  # billion CFU
            },
            cost_per_unit=1.20,
        ),
        Supplement(
            name="Iron",
            brand="Gentle Iron",
            form="capsule",
            nutrients={
                "Iron": 25,  # mg
                "Vitamin C": 60,  # mg (for absorption)
            },
            cost_per_unit=0.18,
        ),
    ]

    # Daily requirements for adult male, age 30-50
    daily_requirements = DailyRequirement(
        age=35,
        gender="male",
        requirements={
            "Vitamin A": 900,  # mcg
            "Vitamin C": 90,  # mg
            "Vitamin D": 15,  # mcg
            "Vitamin E": 15,  # mg
            "Vitamin B12": 2.4,  # mcg
            "Calcium": 1000,  # mg
            "Iron": 8,  # mg
            "Magnesium": 400,  # mg
            "Omega-3 EPA": 250,  # mg
            "Omega-3 DHA": 250,  # mg
            "Probiotics": 10,  # billion CFU
        },
    )

    return supplements, daily_requirements


def main():
    """Demonstrate the supplement optimization model."""
    print("🧬 Supplement Optimization Model")
    print("=" * 50)
    print("⚠️  DISCLAIMER: This is for educational purposes only.")
    print("   Always consult a healthcare provider before changing supplements.")
    print("=" * 50)

    # Create sample data
    supplements, daily_req = create_sample_data()

    # Initialize optimizer
    optimizer = SupplementOptimizer()
    optimizer.set_daily_requirements(daily_req)

    # Add supplements
    for supplement in supplements:
        optimizer.add_supplement(supplement)

    print(f"📊 Available supplements: {len(supplements)}")
    print(f"🎯 Nutrients to optimize: {len(daily_req.requirements)}")

    # Solve for minimum number of pills
    print("\n" + "=" * 50)
    print("🔍 OPTIMIZING FOR MINIMUM NUMBER OF PILLS")
    print("=" * 50)

    result_pills = optimizer.solve_minimum_pills(allow_fractional=True)
    optimizer.print_solution(result_pills)

    # Solve for minimum cost
    print("\n" + "=" * 50)
    print("🔍 OPTIMIZING FOR MINIMUM COST")
    print("=" * 50)

    result_cost = optimizer.solve_minimum_cost()
    optimizer.print_solution(result_cost)

    # Solve for integer solutions (whole pills only)
    print("\n" + "=" * 50)
    print("🔍 OPTIMIZING FOR MINIMUM PILLS (WHOLE PILLS ONLY)")
    print("=" * 50)

    result_integer = optimizer.solve_minimum_pills(allow_fractional=False)
    optimizer.print_solution(result_integer)


if __name__ == "__main__":
    main()
