name: opt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-lru=2.0.2
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - brotli-python=1.0.9
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - comm=0.1.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - flit-core=3.9.0
  - glpk=5.0
  - gmp=6.2.1
  - idna=3.4
  - importlib-metadata=6.7.0
  - importlib_metadata=6.7.0
  - importlib_resources=5.12.0
  - ipykernel=6.24.0
  - ipython=8.14.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonschema=4.17.3
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.23.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=13.1.0
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.0
  - nbclient=0.8.0
  - nbconvert-core=7.6.0
  - nbformat=5.9.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook-shim=0.2.3
  - openssl=3.1.1
  - overrides=7.3.1
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.8.0
  - ply=3.11
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyomo=6.6.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - urllib3=2.0.3
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
